### PR TITLE
Implementation of PHEP process

### LINKED ISSUE #24: Automation/process support needed for PHEPs
I'm opening this issue to capture technical and process implementation needed to support the PHEP  process (#22). The technical details of implementation should be able to change without having to revisit the PHEP so it seems worth separating that implementation discussion out. Opening here because it's likely to interact with #23, but a fair bit of implementation probably will live in [heliophysicsPy/heliophysicsPy.github.io](/heliophysicsPy/heliophysicsPy.github.io).

TODO list (is anything missing?)

- [ ] Index of PHEPs on the main website
- [ ] Auto-builder of PHEPs, maybe to put them on the website?
- [ ] Minting of DOIs as PHEPs are Final. Needs to be tied to the _file_ not just the repo, but should also connect to the repo/commit ID somehow. Do we just upload the file itself? MD, PDF, both? (Note that there may be supplemental files beyond the MD itself.)
- [ ] Handling of DOI updates for "superseded", this can be punted a bit to the future but don't want to paint ourselves into a corner now....
- [ ] Auto-checking of formatting, spelling, proofreading...
- [ ] Set up the `phep-editors` group and permissions
- [ ] Merge vs. rebase (should _not_ do squash commit because history should be maintained)

### PR DESCRIPTION
**Pull request by jtniehof**
This PR has instructions and light automation for the process of releasing PHEPs on approval; see #22. This is the minimum to get things rolling, *not* perfection, which can come later. https://github.com/heliophysicsPy/heliophysicsPy.github.io/pull/328 handles the website end. Nonetheless, going to say this closes #24 .

### CODE REVIEW

**Comment by jtniehof** [comment]
I will make updates here as I work through the process on PHEP 1, and then request merge.

**Comment by jtniehof** [comment]
I've gone through most of the Zenodo work, so I think this is suitable for review and eventual merging.

**Comment by jtniehof** [comment]
Once #22 is merged and the release marked, I'll mark heliophysicsPy/heliophysicsPy.github.io#328 ready for review. Once that's merged, we'll have gone through the whole process, and we can finally merge this.

**Comment by jtniehof** [comment]
So the only downside here is the Zenodo record shows "No description" but I think we can think of potential improvements later.

**Review by sapols — APPROVED** [review]

**Pull request merged**
